### ISSUE TITLE
[Palestra Remota] - Nesta apresentação será mostrado como o Machine Learning foi usado na criação de um preditor de churn.

### ISSUE THREAD

**Issue by matheusfrancisco** [gupy-io/mentoria-python#4]
## Github: ```https://github.com/GabsGear ```
Descrição: ```Customer churn é uma métrica de negócio que mede a taxa de cancelamento ou evasão dos Clientes. Um alto índice de churn impacta em perda de receita e aumento de custos para a aquisição de novos usuários. 
Conseguir identificar quais usuários são mais propensos a "churnar" (preditor de churn) e poder tomar medidas preventivas é o sonho de muitas empresas e pode conferir uma importante vantagem competitiva para a organização. 
Nesta apresentação será mostrado como o Machine Learning foi usado na criação de um preditor de churn. Serão abordados também quais foram os principais desafios do projeto, quais a técnicas de feature engineering utilizadas e os principais algoritmos testados.```

## Obs: Gabriel é um amigo  e concordou em dar essa palestra remota para nossa mentoria de python.

**Comment by deniscostadsc** [comment]
@matheusfrancisco, o Gabriel é seu amigo?

**Comment by matheusfrancisco** [comment]
Sim

**Comment by matheusfrancisco** [comment]
Essa palestra foi apresentada e gravada, embreve mandaremos o link!
